import { config as loadEnv } from "dotenv";
import { z } from "zod";

loadEnv();

const RNS_V2_START_BLOCK = 49_715_519n;

const envSchema = z.object({
  NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  DATABASE_URL: z.string().min(1),
  DATABASE_SSL: z.coerce.boolean().default(true),
  PORT: z.coerce.number().int().positive().optional(),
  CHAT_API_PORT: z.coerce.number().int().positive().default(8788),
  CHAT_CORS_ORIGIN: z.string().min(1).default("*"),
  CHAT_RATE_LIMIT_WINDOW_SECONDS: z.coerce.number().int().positive().default(60),
  CHAT_RATE_LIMIT_MAX_REQUESTS: z.coerce.number().int().positive().default(12),
  CHAT_GUEST_PROMPT_LIMIT: z.coerce.number().int().positive().default(5),
  CHAT_INPUT_MAX_CHARS: z.coerce.number().int().positive().default(600),
  CHAT_OUTPUT_MAX_TOKENS_FAST: z.coerce.number().int().positive().default(160),
  CHAT_OUTPUT_MAX_TOKENS_DEEP: z.coerce.number().int().positive().default(320),
  STAGE0_API_PUBLIC_URL: z.string().url().optional(),
  STAGE0_UPLOAD_MAX_BYTES: z.coerce.number().int().positive().default(2 * 1024 * 1024),
  STAGE0_DOCS_BASE_URL: z.string().url().default("https://stagezerolabs.gitbook.io/stage0"),
  STAGE0_DOCS_SEED_URLS: z.string().default(""),
  RISE_TESTNET_RPC_URL: z.string().url().default("https://testnet.riselabs.xyz"),
  RISE_TESTNET_CHAIN_ID: z.coerce.number().int().positive().default(11155931),
  RISE_TESTNET_EXPLORER_URL: z.string().url().default("https://explorer.testnet.riselabs.xyz"),
  RNS_REGISTRY_ADDRESS: z.string().regex(/^0x[a-fA-F0-9]{40}$/).default("0x18E2B26E04B624131630355f00655330FAcb3d0C"),
  RNS_RESOLVER_ADDRESS: z.string().regex(/^0x[a-fA-F0-9]{40}$/).default("0x50593CAB471272c0D67014F6233eAcb897F5d705"),
  RNS_REGISTRAR_ADDRESS: z.string().regex(/^0x[a-fA-F0-9]{40}$/).default("0x87e6e5fA7E63fF008d8Dc5347503a8ED5d6bdA77"),
  RNS_AUCTION_HOUSE_ADDRESS: z.string().regex(/^0x[a-fA-F0-9]{40}$/).default("0xaCb8DE38FD057ed8288BAa6AE60434FBB5f1DEd0"),
  RNS_MARKETPLACE_ADDRESS: z.string().regex(/^0x[a-fA-F0-9]{40}$/).default("0x92b421f992892e26074e9529f61acf1b86f13bd7"),
  RNS_SYNC_INTERVAL_SECONDS: z.coerce.number().int().positive().default(180),
  RNS_AUCTION_LIFECYCLE_INTERVAL_SECONDS: z.coerce.number().int().min(60).max(300).default(180),
  RNS_RECONCILE_INTERVAL_SECONDS: z.coerce.number().int().positive().default(12 * 60 * 60),
  RNS_SYNC_CHUNK_SIZE: z.coerce.number().int().positive().default(5_000),
  RNS_REGISTRY_START_BLOCK: z.coerce.bigint().nonnegative().default(RNS_V2_START_BLOCK),
  RNS_RESOLVER_START_BLOCK: z.coerce.bigint().nonnegative().default(RNS_V2_START_BLOCK),
  RNS_REGISTRAR_START_BLOCK: z.coerce.bigint().nonnegative().default(RNS_V2_START_BLOCK),
  RNS_AUCTION_HOUSE_START_BLOCK: z.coerce.bigint().nonnegative().default(RNS_V2_START_BLOCK),
  RNS_MARKETPLACE_START_BLOCK: z.coerce.bigint().nonnegative().default(RNS_V2_START_BLOCK),
  RNS_PRICE_SIGNER_PRIVATE_KEY: z.string().regex(/^0x[a-fA-F0-9]{64}$/).optional(),
  RNS_PRICE_QUOTE_TTL_SECONDS: z.coerce.number().int().positive().default(300),
  RNS_PRICE_SOURCE_URL: z.string().url().default("https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=usd"),
  RNS_PRICE_SOURCE_REFRESH_INTERVAL_MS: z.coerce.number().int().positive().default(60_000),
  RNS_PRICE_SETTER_PRIVATE_KEY: z.string().regex(/^0x[a-fA-F0-9]{64}$/).optional(),
  RESEND_API_KEY: z.string().optional(),
  RESEND_FROM_EMAIL: z.string().email().default("hello@stage0.xyz"),
  RNS_ADMIN_ACTIVITY_SLACK_WEBHOOK_URL: z.string().url().optional(),
  RNS_PUBLIC_API_RATE_LIMIT_WINDOW_SECONDS: z.coerce.number().int().positive().default(60),
  RNS_PUBLIC_API_RATE_LIMIT_MAX_REQUESTS: z.coerce.number().int().positive().default(60),
  STAGE0_APP_URL: z.string().url().default("https://stage0.xyz"),
  STAGE0_X_URL: z.string().url().default("https://x.com/stage0_"),
  STAGE0_DISCORD_URL: z.string().url().default("https://discord.gg/jkPT89fA8d"),
  DEEPSEEK_API_KEY: z.string().optional(),
  DEEPSEEK_BASE_URL: z.string().url().default("https://api.deepseek.com"),
  DEEPSEEK_MODEL_FAST: z.string().min(1).default("deepseek-v4-flash"),
  DEEPSEEK_MODEL_COMPLEX: z.string().min(1).default("deepseek-v4-pro"),
  ASSEMBLYAI_API_KEY: z.string().optional(),
});

const env = envSchema.parse(process.env);
const MAX_PROJECT_IMAGE_BYTES = 2 * 1024 * 1024;

export const config = {
  nodeEnv: env.NODE_ENV,
  databaseUrl: env.DATABASE_URL,
  databaseSsl: env.DATABASE_SSL,
  port: env.PORT ?? env.CHAT_API_PORT,
  corsOrigin: env.CHAT_CORS_ORIGIN,
  rateLimitWindowSeconds: env.CHAT_RATE_LIMIT_WINDOW_SECONDS,
  rateLimitMaxRequests: env.CHAT_RATE_LIMIT_MAX_REQUESTS,
  guestPromptLimit: env.CHAT_GUEST_PROMPT_LIMIT,
  chatInputMaxChars: env.CHAT_INPUT_MAX_CHARS,
  chatOutputMaxTokensFast: env.CHAT_OUTPUT_MAX_TOKENS_FAST,
  chatOutputMaxTokensDeep: env.CHAT_OUTPUT_MAX_TOKENS_DEEP,
  apiPublicBaseUrl:
    env.STAGE0_API_PUBLIC_URL?.replace(/\/$/, "") ??
    `http://localhost:${env.PORT ?? env.CHAT_API_PORT}`,
  uploadMaxBytes: Math.min(env.STAGE0_UPLOAD_MAX_BYTES, MAX_PROJECT_IMAGE_BYTES),
  docsBaseUrl: env.STAGE0_DOCS_BASE_URL.replace(/\/$/, ""),
  docsSeedUrls: env.STAGE0_DOCS_SEED_URLS
    .split(",")
    .map((value) => value.trim())
    .filter(Boolean),
  riseTestnetRpcUrl: env.RISE_TESTNET_RPC_URL,
  riseTestnetChainId: env.RISE_TESTNET_CHAIN_ID,
  riseTestnetExplorerUrl: env.RISE_TESTNET_EXPLORER_URL.replace(/\/$/, ""),
  rnsContracts: {
    registry: env.RNS_REGISTRY_ADDRESS.toLowerCase(),
    resolver: env.RNS_RESOLVER_ADDRESS.toLowerCase(),
    registrar: env.RNS_REGISTRAR_ADDRESS.toLowerCase(),
    auctionHouse: env.RNS_AUCTION_HOUSE_ADDRESS.toLowerCase(),
    marketplace: env.RNS_MARKETPLACE_ADDRESS.toLowerCase(),
  },
  rnsSyncIntervalSeconds: env.RNS_SYNC_INTERVAL_SECONDS,
  rnsAuctionLifecycleIntervalSeconds: env.RNS_AUCTION_LIFECYCLE_INTERVAL_SECONDS,
  rnsReconcileIntervalSeconds: env.RNS_RECONCILE_INTERVAL_SECONDS,
  rnsSyncChunkSize: env.RNS_SYNC_CHUNK_SIZE,
  rnsStartBlocks: {
    registry: env.RNS_REGISTRY_START_BLOCK,
    resolver: env.RNS_RESOLVER_START_BLOCK,
    registrar: env.RNS_REGISTRAR_START_BLOCK,
    primaryAuction: env.RNS_AUCTION_HOUSE_START_BLOCK,
    marketplace: env.RNS_MARKETPLACE_START_BLOCK,
  },
  rnsPriceSignerPrivateKey: env.RNS_PRICE_SIGNER_PRIVATE_KEY,
  rnsPriceQuoteTtlSeconds: env.RNS_PRICE_QUOTE_TTL_SECONDS,
  rnsPriceSourceUrl: env.RNS_PRICE_SOURCE_URL,
  rnsPriceSourceRefreshIntervalMs: env.RNS_PRICE_SOURCE_REFRESH_INTERVAL_MS,
  rnsPriceSetterPrivateKey: env.RNS_PRICE_SETTER_PRIVATE_KEY,
  resendApiKey: env.RESEND_API_KEY,
  resendFromEmail: env.RESEND_FROM_EMAIL,
  rnsAdminActivitySlackWebhookUrl: env.RNS_ADMIN_ACTIVITY_SLACK_WEBHOOK_URL,
  rnsPublicApiRateLimitWindowSeconds: env.RNS_PUBLIC_API_RATE_LIMIT_WINDOW_SECONDS,
  rnsPublicApiRateLimitMaxRequests: env.RNS_PUBLIC_API_RATE_LIMIT_MAX_REQUESTS,
  stage0AppUrl: env.STAGE0_APP_URL.replace(/\/$/, ""),
  stage0XUrl: env.STAGE0_X_URL.replace(/\/$/, ""),
  stage0DiscordUrl: env.STAGE0_DISCORD_URL.replace(/\/$/, ""),
  deepseekApiKey: env.DEEPSEEK_API_KEY,
  deepseekBaseUrl: env.DEEPSEEK_BASE_URL.replace(/\/$/, ""),
  deepseekModelFast: env.DEEPSEEK_MODEL_FAST,
  deepseekModelComplex: env.DEEPSEEK_MODEL_COMPLEX,
  assemblyAiApiKey: env.ASSEMBLYAI_API_KEY,
} as const;
